FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

COPY . .

EXPOSE 5000

# Run the application
CMD ["python", "no-ty-api.py"]
